// constants/gamification.js — XP levels, ranks, verses, badges (athlete-side content)
export const LVLSTEP=300;
export const lvlOf=xp=>1+Math.floor((xp||0)/LVLSTEP);
export const lvlPct=xp=>Math.round(((xp||0)%LVLSTEP)/LVLSTEP*100);
export const toNext=xp=>LVLSTEP-((xp||0)%LVLSTEP);
export const RANKS=["Rookie","Builder","Grinder","Athlete","Warrior","Beast","Elite","Legend","Icon"];
export const rankOf=xp=>RANKS[Math.min(RANKS.length-1,lvlOf(xp)-1)];
export const MAINLIFTS=["Back Squat","Barbell Bench Press","Conventional Deadlift","Overhead Press","Barbell Row","Front Squat"];
export const VERSES=[
  ["Philippians 4:13","Strength for this set isn't self-made. Show up — finish what you started."],
  ["1 Corinthians 9:27","Discipline the body. Not from shame — from purpose."],
  ["Proverbs 21:5","Steady plans beat frantic effort. Log it. Repeat it. Trust it."],
  ["Isaiah 40:31","Recovery is part of the work. Rest so you can rise."],
  ["Galatians 6:9","Don't quit in the boring middle. The harvest comes to those who stay."],
  ["1 Timothy 4:8","Train the body. Train the soul harder. Both, today."],
  ["Colossians 3:23","Whatever the lift — give it real effort, as worship, not for applause."],
  ["Isaiah 41:10","Fear not — He strengthens you, He holds you up. Step under the bar."],
  ["2 Corinthians 12:9","His power shows up best right where you're weakest. Lean in."],
  ["Ephesians 6:10","Real strength is borrowed strength. Plug into Him before you load up."],
  ["Joshua 1:9","Be strong and courageous — He's already in the room you're walking into."],
  ["Hebrews 12:11","Discipline stings now, pays peace later. Pay the tax today."],
  ["James 1:12","The load you're under is making you. Stay under it a little longer."],
  ["Romans 12:2","Change the inputs, change the man. Renew your mind on purpose."],
  ["Psalm 139:14","You're not a problem to fix — you're fearfully made. Steward it."],
  ["2 Timothy 1:7","Fear's not from Him. Power, love, a clear head — those are yours."],
  ["Matthew 11:28","Carrying too much? Bring it to Him. Rest starts there."],
  ["Proverbs 27:17","You weren't built to grind alone. Find your iron, sharpen each other."],
  ["1 Corinthians 10:31","Even this rep can be worship. Do it like He's watching — He is."],
  ["Hebrews 12:1","Drop the dead weight. Run your race, not the guy's beside you."],
  ["Psalm 18:32","The strength to train is issued by Him. Use it well today."],
  ["Romans 5:3","This isn't pointless pain. Suffering's building endurance in you."],
  ["Psalm 127:2","Grinding with no rest is unbelief with calluses. Sleep. Trust. Grow."],
  ["Philippians 4:8","Garbage in, garbage out — thoughts too. Feed the mind what's true."],
  ["Ephesians 2:10","You're His handiwork, made for good work. Go do some today."],
  ["Deuteronomy 31:6","He won't leave you. Neither do you — finish the set."],
  ["1 Corinthians 9:24","Don't jog through your one shot. Run like the prize is real — it is."],
  ["Lamentations 3:23","Yesterday's misses are gone. Fresh mercy every sunrise. Start clean."],
  ["Nehemiah 8:10","Joy isn't the reward for the work. It's the fuel for it."],
  ["2 Corinthians 5:17","The old you doesn't set today's ceiling. New creation, new reps."],
  ["Proverbs 3:5","Stop overthinking the plan. Trust Him, follow it, watch it work."],
  ["Hebrews 10:36","You don't need more talent today. You need to not stop."],
  ["Psalm 46:1","When it all gets heavy, He's the steady place. Plant there, then push."],
  ["1 Corinthians 6:19","This body's on loan, bought at a price. Honor it — don't trash it."],
  ["Isaiah 43:2","Deep water today? You won't drown. He's wading in with you."],
  ["2 Timothy 4:7","Finish what you started. Future-you wants to say 'I didn't quit.'"],
  ["Colossians 3:2","Lift your eyes higher than the mirror. Aim the mind up."],
  ["Psalm 73:26","Body fails, will fades — He's the strength underneath both. Train on."],
  ["James 1:3","Resistance is the curriculum, not the punishment. Don't skip class."],
  ["Romans 8:37","You're not barely surviving this. In Him you're winning it."],
  ["Proverbs 16:3","Hand Him the plan before you start. Then go to work."],
  ["Isaiah 40:29","Empty tank? That's His specialty. Show up faint, leave filled."],
  ["Matthew 6:33","Put Him first and the rest lines up. Order matters."],
  ["1 Corinthians 15:58","Nothing you put in today is wasted. Keep stacking."],
  ["Galatians 2:20","It's not you white-knuckling this — Christ lives in you. Loosen the grip."],
  ["Psalm 27:1","If He's got you, what exactly are you afraid of? Step up."],
  ["Proverbs 24:16","Fall down seven, get up eight. The rising is the whole point."],
  ["Romans 15:13","Run on hope, not fumes. Let Him top off the tank."],
  ["2 Corinthians 10:5","That defeated thought? Cuff it. You command it, not the reverse."],
  ["Hebrews 4:9","Stop striving to prove yourself. Train from rest, not for it."],
  ["Philippians 2:3","Lift others up in here, not just iron. Check the ego at the door."],
  ["Isaiah 26:3","Peace isn't fewer problems. It's a mind anchored on Him."],
  ["Luke 16:10","Win the small reps no one sees. Big things are built there."],
  ["Psalm 23:2","Sometimes growth means being made to stop. Let the rest day work."],
  ["2 Timothy 2:5","No shortcuts, no half-reps. The crown goes to those who do it right."],
  ["Romans 8:1","Missed yesterday? No condemnation here. Start clean today."],
  ["Proverbs 12:1","Hate correction and you stay stuck. Love it and you grow."],
  ["Jeremiah 29:11","He's not winging your story. There's a future in it — keep walking."],
  ["Psalm 30:5","Hard night? Joy comes in the morning. Don't quit in the dark."],
  ["1 Thessalonians 5:18","Sore, tired, behind? Still — name what's good. Gratitude changes the lift."],
  ["Habakkuk 3:19","He makes your feet sure on hard ground. Climb."],
  ["Romans 12:1","Lay the body on the altar. The training is the offering."],
  ["Proverbs 4:23","Guard what you let in. Everything flows from the heart."],
  ["Mark 6:31","Even He pulled the team away to rest. Take the deload."],
  ["1 Peter 1:13","Roll up your sleeves mentally. The work starts in the head."],
  ["Psalm 90:12","You've got a set number of days. Spend today like it counts."],
  ["Galatians 5:13","Strength's for serving, not flexing. Carry someone today."],
  ["Proverbs 25:28","No self-control and everything leaks. Build the walls back, one rep."],
  ["2 Corinthians 4:16","Body's tired, sure. The inner man's getting stronger. Press on."],
  ["Psalm 56:3","Scared and showing up beats brave and absent. Trust, then move."],
  ["Ecclesiastes 4:9","Solo's slower. Pick a partner, share the load, go further."],
  ["Zephaniah 3:17","He's not disappointed in you — He's singing over you. Train glad."],
  ["Proverbs 14:23","Talk is cheap, sweat pays. Less mouth, more work."],
  ["John 15:5","On your own you'll stall. Stay connected to Him, bear fruit."],
  ["Psalm 118:24","You woke up — that's grace. Rejoice, then go to work."],
  ["Isaiah 41:13","He's got the hand you need. Reach for the bar."],
  ["Romans 8:6","Where your mind camps, you'll live. Pitch the tent in life."],
  ["Proverbs 13:4","Wishing builds nothing. Working does. Be the diligent one."],
  ["Philippians 1:6","He who started the work in you will finish it. Keep showing up."],
  ["1 John 3:1","You're a son, not a slave. Train from being loved, not for it."],
  ["Ephesians 5:16","Time's the one rep you can't redo. Don't waste today."],
  ["Psalm 121:2","Where's your help from? The One who made heaven and earth. Look up."],
  ["Mark 12:30","All your strength belongs to Him — including what's left in the tank."],
  ["James 1:17","The body that moves, the breath in your lungs — gifts. Use them well."],
  ["Proverbs 18:10","His name's a strong tower. Run there when you've run yourself out."],
  ["Psalm 28:7","He's your strength and shield. Trust Him and your heart finds its second wind."],
  ["Colossians 1:11","Strengthened with all power for endurance and patience. Pray that over today."],
  ["1 Corinthians 16:13","Stay alert, stand firm, be strong. Three orders — obey them today."],
  ["Psalm 31:24","Be strong, take heart, you who wait on Him. The waiting isn't wasted."],
  ["Romans 8:31","If God is for you, who's against you? Load the bar."]
];
export const verseToday=()=>VERSES[Math.floor(Date.now()/864e5)%VERSES.length];
export const BADGES=[
  {id:"first_lift",ic:"🏋️",l:"First Rep",d:"Log a session"},
  {id:"ten_lifts",ic:"🔟",l:"Consistent",d:"Log 10 sessions"},
  {id:"perfect_day",ic:"🎯",l:"Perfect Day",d:"All 7 pillars in a day"},
  {id:"on_fire",ic:"🔥",l:"On Fire",d:"7-day streak"},
  {id:"first_pr",ic:"📈",l:"Record Breaker",d:"Set a PR"},
  {id:"reflective",ic:"📋",l:"Reflective",d:"Submit a check-in"},
  {id:"fueled",ic:"🥗",l:"Dialed In",d:"Log 10 meals"},
  {id:"lvl5",ic:"⭐",l:"Level 5",d:"Reach Level 5"}
];
