// constants/pillars.js — 7 Pillars framework data
export const PILL=[["fitness","🏋️","#FF6B2C"],["nutrition","🥗","#3AE07A"],["sleep","😴","#3AE0FF"],["stress","🧘","#A78BFA"],["mindset","🧠","#FFB23A"],["habits","🔄","#FF3A8E"],["spirit","✝️","#34D399"]];
export const PILLARS=[
  {id:"fitness",name:"Fitness",icon:"🏋️",color:"#FF6B2C",tag:"Train with intent.",why:"Strength is the currency of a long life. Move heavy things, often — your future self is built in these reps.",verse:["1 Cor 9:27","Discipline the body — not from shame, from purpose."],actions:[{id:"f1",label:"Completed today's session (or 20+ min of real movement)"},{id:"f2",label:"Hit 8,000+ steps"},{id:"f3",label:"5 min mobility or warm-up"}]},
  {id:"nutrition",name:"Nutrition",icon:"🥗",color:"#3AE07A",tag:"Fuel the work.",why:"You can't out-train a sloppy plate. Protein first, whole foods, repeat — keep it boring and it works.",verse:["1 Cor 10:31","Even eating is worship when it's done on purpose."],actions:[{id:"n1",label:"Hit your protein target"},{id:"n2",label:"2+ servings of veg or fruit"},{id:"n3",label:"No mindless grazing after dinner"}]},
  {id:"sleep",name:"Sleep",icon:"😴",color:"#3AE0FF",tag:"Recover or stall.",why:"Sleep is where the gains land. Skip it and you're just spinning your wheels with great form.",verse:["Psalm 127:2","Rest isn't weakness — striving without it is."],actions:[{id:"s1",label:"7+ hours in bed"},{id:"s2",label:"Screens off 30 min before bed"},{id:"s3",label:"Woke at a consistent time"}]},
  {id:"stress",name:"Stress",icon:"🧘",color:"#A78BFA",tag:"Manage the load.",why:"Unmanaged stress quietly eats your recovery and your peace. Build a valve before you need it.",verse:["Matthew 6:34","Carry today. Tomorrow has enough of its own."],actions:[{id:"st1",label:"5 min breathwork or stillness"},{id:"st2",label:"Got outside for a walk"},{id:"st3",label:"Held one boundary / took one thing off your plate"}]},
  {id:"mindset",name:"Mindset",icon:"🧠",color:"#FFB23A",tag:"Renew the mind.",why:"Your self-talk sets your ceiling. Train it like any other muscle — on purpose, every day.",verse:["Romans 12:2","Don't coast on autopilot — renew how you think."],actions:[{id:"m1",label:"Named one win today"},{id:"m2",label:"Reframed one negative thought"},{id:"m3",label:"5 min reading or learning"}]},
  {id:"habits",name:"Habits",icon:"🔄",color:"#FF3A8E",tag:"Stack the small.",why:"You don't rise to your goals; you fall to your systems. Win the boring reps and the rest follows.",verse:["Proverbs 21:5","Steady plans beat frantic effort."],actions:[{id:"h1",label:"Did your keystone habit"},{id:"h2",label:"Prepped tomorrow (food / clothes / plan)"},{id:"h3",label:"One deep block with the phone out of reach"}]},
  {id:"spirit",name:"Spirituality",icon:"✝️",color:"#34D399",tag:"Anchor the soul.",why:"Train the body, train the soul harder. Both, today — one without the other leaves you hollow.",verse:["1 Tim 4:8","Bodily training has value; godliness holds value for everything."],actions:[{id:"sp1",label:"Prayer or quiet time"},{id:"sp2",label:"Read Scripture"},{id:"sp3",label:"Gratitude — named three"}]}
];
export const PILLAR_ACTS=Object.fromEntries(PILLARS.map(p=>[p.id,p.actions.map(a=>a.id)]));
